  
USE [WISE_STAGING]
GO
 
CREATE TABLE [dbo].[T_MKT_MARKETPLACE_APILOGREQUEST](
	[T_MKT_MARKETPLACE_APILOGREQUEST_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_NAME] [varchar](200) NULL,
	[ORDER_ID] [varchar](100) NULL, 
	[PARAMETER] [nvarchar](max) NULL,
	[REQUEST_DT] [datetime] NULL,
	[RESPONSE_ID] [varchar](500) NULL,
	[DTM_CRT] [datetime] NULL,
	[USR_CRT] [varchar](100) NULL
)

create index idx_ORDER_ID_T_MKT_MARKETPLACE_APILOGREQUEST on T_MKT_MARKETPLACE_APILOGREQUEST (ORDER_ID) 
create index idx_RESPONSE_ID_T_MKT_MARKETPLACE_APILOGREQUEST on T_MKT_MARKETPLACE_APILOGREQUEST (RESPONSE_ID)
 
 /*
 DROP TABLE [T_MKT_MARKETPLACE_APILOGREQUEST]
 DROP TABLE [T_MKT_MARKETPLACE_APILOGRESPONSE]
 */