  
USE [WISE_STAGING]
GO
 
CREATE TABLE [dbo].[T_MKT_MARKETPLACE_APILOGRESPONSE](
	[T_MKT_MARKETPLACE_APILOGRESPONSE_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_NAME] [varchar](200) NULL,
	[ORDER_ID] [varchar](100) NULL,
	[TRANSACTION_ID] [varchar](100) NULL,
	[RESPONSE_CODE] [varchar](3) NULL,
	[RESPONSE_MESSAGE] [nvarchar](max) NULL,
	[ERROR_DESC] [varchar](max) NULL,
	[RESPONSE_DT] [datetime] NULL,
	[RESPONSE_ID] [varchar](500) NULL,
	[DTM_CRT] [datetime] NULL,
	[USR_CRT] [varchar](100) NULL,
	[PARAMETER] [nvarchar](max) NULL
)  

create index idx_ORDER_ID_T_MKT_MARKETPLACE_APILOGRESPONSE on T_MKT_MARKETPLACE_APILOGRESPONSE (ORDER_ID)
create index idx_TRANSACTION_ID_T_MKT_MARKETPLACE_APILOGRESPONSE on T_MKT_MARKETPLACE_APILOGRESPONSE (TRANSACTION_ID)
create index idx_RESPONSE_ID_T_MKT_MARKETPLACE_APILOGRESPONSE on T_MKT_MARKETPLACE_APILOGRESPONSE (RESPONSE_ID)

 /*
 DROP TABLE [T_MKT_MARKETPLACE_APILOGREQUEST]
 DROP TABLE [T_MKT_MARKETPLACE_APILOGRESPONSE]
 */